import StyleDictionary from 'style-dictionary';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = resolve(__dirname);

// Minimal custom format: extends standard css/variables with theme grouping
// Only customizes theme structure, uses standard token processing
//
// because the Figma export doesn't follow Style Dictionary standard format
// (missing 'value' property). Once the Figma export is fixed to include 'value'
// and 'type: "typography"', this custom handling can be removed and Style Dictionary
// will process typography tokens automatically using standard transforms.
//
// and transform engine. It should be replaced with standard SD processing once
// the source format is corrected in the Figma export pipeline.
StyleDictionary.registerFormat({
  name: 'css/variables-themes',
  format: ({ dictionary, options }) => {
    const { selector = ':root' } = options;
    
    // Group tokens by theme using standard dictionary.allTokens
    const lightColors = [];
    const darkColors = [];
    const sharedTokens = [];
    
    dictionary.allTokens.forEach(token => {
      const path = token.path.join('-');
      if (path.startsWith('color-md-sys-light-')) {
        lightColors.push(token);
      } else if (path.startsWith('color-md-sys-dark-')) {
        darkColors.push(token);
      } else {
        sharedTokens.push(token);
      }
    });
    
    // This is the only non-standard part due to tokens.json structure.
    // Expected format: { "display-large": { "value": {...}, "type": "typography" } }
    // Current format: { "display-large": { "font-family": "...", "font-size": "..." } }
    // Once Figma export is fixed, Style Dictionary will process these automatically.
    const tokensPath = resolve(rootDir, 'src/tokens/tokens.json');
    const tokensData = JSON.parse(readFileSync(tokensPath, 'utf-8'));
    const typographyVars = [];
    
    if (tokensData.typography?.md?.sys?.typescale) {
      for (const [scaleName, scaleProps] of Object.entries(tokensData.typography.md.sys.typescale)) {
        if (scaleProps && typeof scaleProps === 'object') {
          for (const [prop, value] of Object.entries(scaleProps)) {
            if (value !== null && typeof value !== 'object') {
              typographyVars.push(`  --md-sys-typescale-${scaleName}-${prop}: ${value};`);
            }
          }
        }
      }
    }
    
    let output = `/* Design Tokens - CSS Variables */\n`;
    output += `/* Generated by: Style Dictionary */\n`;
    output += `/* DO NOT EDIT MANUALLY */\n\n`;
    
    // Light theme
    output += `${selector},\n.theme-light {\n`;
    
    // Colors (light theme)
    if (lightColors.length > 0) {
      output += `  /* Color - Light Theme */\n`;
      lightColors.forEach(token => {
        const name = token.path.slice(2).join('-').replace(/^light-/, '');
        output += `  --md-sys-color-${name}: ${token.value};\n`;
      });
      output += `\n`;
    }
    
    if (typographyVars.length > 0) {
      output += `  /* Typography */\n`;
      output += typographyVars.join('\n') + '\n\n';
    }
    
    // Shape and Elevation (shared)
    sharedTokens.forEach(token => {
      const path = token.path.join('-');
      if (path.startsWith('shape-md-sys-corner-')) {
        const name = path.replace('shape-md-sys-corner-', 'corner-');
        output += `  --md-sys-shape-${name}: ${token.value};\n`;
      } else if (path.startsWith('elevation-md-sys-level-')) {
        const name = path.replace('elevation-md-sys-level-', 'level-');
        output += `  --md-sys-elevation-${name}: ${token.value};\n`;
      }
    });
    
    output += `}\n\n`;
    
    // Dark theme
    if (darkColors.length > 0) {
      output += `.theme-dark {\n`;
      output += `  /* Color - Dark Theme */\n`;
      darkColors.forEach(token => {
        const name = token.path.slice(2).join('-').replace(/^dark-/, '');
        output += `  --md-sys-color-${name}: ${token.value};\n`;
      });
      output += `\n  /* Typography, Shape, and Elevation remain the same */\n`;
      output += `}\n`;
    }
    
    return output;
  }
});

export default {
  source: ['src/tokens/tokens.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/styles/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables-themes',
          options: {
            selector: ':root',
          },
        },
      ],
    },
  },
};
